#ifndef CAN_REG_H
#define CAN_REG_H

// TXBnCTRL: TX BUFFER CONTROL REGISTER
#define TXB0CTRL 0x30
#define TXB1CTRL 0x40
#define TXB2CTRL 0x50
#define ABTF  6
#define MLOA  5
#define TXERR 4
#define TXREQ 3
#define TXP1  1
#define TXP0  0

// TXRTSCTRL: TXnRTS PIN CONTROL & STATUS REGISTER
#define TXRTSCTRL 0xD0
#define B2RTS  5
#define B1RTS  4
#define B0RTS  3
#define B2RTSM 2
#define B1RTSM 1
#define B0RTSM 0

// TXBnSIDH: TX BUFFER n STANDARD IDENTIFIER REGISTER HIGH
#define TXB0SIDH 0x31
#define TXB1SIDH 0x41
#define TXB2SIDH 0x51

// TXBnSIDL: TX BUFFER n STANDARD IDENTIFIER REGISTER LOW 
#define TXB0SIDL 0x32
#define TXB1SIDL 0x42
#define TXB2SIDL 0x52

// TXBnEID8: TX BUFFER n EXTENDED IDENTIFIER REGISTER HIGH 
#define TXB0EID8 0x33
#define TXB1EID8 0x43
#define TXB2EID8 0x53

// TXBnEID0: TX BUFFER n EXTENDED IDENTIFIER REGISTER LOW
#define TXB0EID0 0x34
#define TXB1EID0 0x44
#define TXB2EID0 0x54

// TXBnDLC: TX BUFFER n DATA LENGTH CODE REGISTER
#define TXB0DLC 0x35
#define TXB1DLC 0x45
#define TXB2DLC 0x55
#define RTR 6
#define DLC3 3
#define DLC2 2
#define DLC1 1
#define DLC0 0

// TODO: Define TXBnDm

// RXB0CTRL: RX BUFFER 0 CONTROL REGISTER
#define RXB0CTRL 0x60
#define RXM1    6
#define RXM0    5
#define RXRTR   3
#define BUKT    2
#define BUKT1   1
#define FILHIT0 0

// RXB1CTRL: RX BUFFER 1 CONTROL REGISTER
#define RXB1CTRL 0x70
#define RXM1    6
#define RXM0    5
#define RXRTR   3
#define FILHIT2 2
#define FILHIT1 1
#define FILHIT0 0

// TODO: Define BFPCTRL

// RXBnSIDH: RX BUFFER n STANDARD IDENTIFIER REGISTER HIGH
#define RXB0SIDH 0x61
#define RXB1SIDH 0x71

// RXBnSIDL: RX BUFFER n STANDARD IDENTIFIER REGISTER LOW
#define RXB0SIDL 0x62
#define RXB1SIDL 0x72

// RXBnEID8: RX BUFFER n EXTENDED IDENTIFIER REGISTER HIGH
#define RXB0EID8 0x63
#define RXB1EID8 0x73

// RXBnEID0: RX BUFFER n EXTENDED IDENTIFIER REGISTER LOW
#define RXB0EID0 0x64
#define RXB1EID0 0x74

// RXBnDLC: RX BUFFER n DATA LENGTH CODE REGISTER
#define RXB0EID0 0x64
#define RXB1EID0 0x74

// TODO: Define RXBnDm

// RXFnSIDH: FILTER n STANDARD IDENTIFIER REGISTER HIGH
#define RXF0SIDH 0x00
#define RXF1SIDH 0x04
#define RXF2SIDH 0x08
#define RXF3SIDH 0x10
#define RXF4SIDH 0x14
#define RXF5SIDH 0x18

// RXFnSIDL: FILTER n STANDARD IDENTIFIER REGISTER LOW
#define RXF0SIDL 0x01
#define RXF1SIDL 0x05
#define RXF2SIDL 0x09
#define RXF3SIDL 0x11
#define RXF4SIDL 0x15
#define RXF5SIDL 0x19

// RXFnEID8: FILTER n EXTENDED IDENTIFIER REGISTER HIGH
#define RXF0EID8 0x02
#define RXF1EID8 0x06
#define RXF2EID8 0x0A
#define RXF3EID8 0x12
#define RXF4EID8 0x16
#define RXF5EID8 0x1A

// RXFnEID0: FILTER n EXTENDED IDENTIFIER REGISTER LOW
#define RXF0EID0 0x03
#define RXF1EID0 0x07
#define RXF2EID0 0x0B
#define RXF3EID0 0x13
#define RXF4EID0 0x17
#define RXF5EID0 0x1B

// RXMnSIDH: MASK n STANDARD IDENTIFIER REGISTER HIGH
#define RXM0SIDH 0x20
#define RXM1SIDH 0x24

// RXMnSIDL: MASK n STANDARD IDENTIFIER REGISTER LOW
#define RXM0SIDL 0x21
#define RXM1SIDL 0x25

// RXMnEID8: MASK n EXTENDED IDENTIFIER REGISTER HIGH
#define RXM0EID8 0x22
#define RXM1EID8 0x26

// RXMnEID0: MASK n EXTENDED IDENTIFIER REGISTER LOW
#define RXM0EID0 0x23
#define RXM1EID0 0x27

// CNF1: CONFIGURATION REGISTER 1
#define CNF1 0x2A
#define MCU_4MHZ_CLK 0

// CNF2: CONFIGURATION REGISTER 2
#define CNF2 0x29
#define BLTMODE 7
#define SAM     6
#define PHSEG12 5
#define PHSEG11 4
#define PHSEG10 3
#define PRSEG2  2
#define PRSEG1  1
#define PRSEG0  0

// CNF3: CONFIGURATION REGISTER 3
#define CNF3 0x28
#define SOF     7
#define WAKFIL  6
#define PHSEG22 2
#define PHSEG21 1
#define PHSEG20 0

// TEC: TX ERROR COUNTER REGISTER
#define TEC 0x1C

// REC: RX ERROR COUNTER REGISTER
#define REC 0x1D

// EFLG: ERROR FLAG REGISTER
#define EFLG 0x2D
#define RX1OVR 7
#define RX0OVR 6
#define TXBO   5
#define TXEP   4
#define RXEP   3
#define TXWAR  2
#define RXWAR  1
#define EWARN  0

// CANINTE: CAN INTERRUPT ENABLE REGISTER
#define CANINTE 0x2B
#define MERRE 7
#define WAKIE 6
#define ERRIE 5
#define TX2IE 4
#define TX1IE 3
#define TX0IE 2
#define RX1IE 1
#define RX0IE 0

// CANINTF: CAN INTERRUPT FLAG REGISTER
#define CANINTF 0x2C
#define MERRF 7
#define WAKIF 6
#define ERRIF 5
#define TX2IF 4
#define TX1IF 3
#define TX0IF 2
#define RX1IF 1
#define RX0IF 0

// CANCTRL: CAN CONTROL REGISTER
#define CANCTRL 0x0F
#define ABAT    4
#define OSM     3
#define CLKEN   2
#define CLKPRE1 1
#define CLKPRE0 0

// CANSTAT: CAN STATUS REGISTER
#define CANSTAT 0x0E

#endif	// CAN_REG_H
